# Setup
title:               Moustafa Sebaa
tagline:             'PhD Candidate'
description:         'Eager to adress challenges related to granular & porous media using numerical and experimental techniques. Check <a href="https://msebaa.github.io/" target="_blank">this</a>.'
url:                 https://msebaa.github.io #http://lanyon.getpoole.com
baseurl:             '/sebaam'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Moustafa Sebaa
  url:               https://twitter.com/MustaSebaa
  email:             sebaamoustafa@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
